/**
 * 武将基础数据
 * 立绘：extension/群友设计/image/character/{武将id}.jpg（由 patchCharacterAssets 自动写入 img）
 */
export const characterData = {
	qunyou_zoushi: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_shehun", "qunyou_zhandeng"],
	},
	qunyou_wenyang: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_youlong", "qunyou_fuzhen"],
	},
	qunyou_shibao: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_cuisheng"],
	},
	qunyou_sunxiu: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_rongguo"],
	},
	wending_clan_xiedaoyun: {
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["wending_yongxu", "wending_miaoyu", "clanshuze"],
	},
	wending_clan_xiean: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["wending_yanghui", "wending_yaliang", "clanshuze"],
	},
	wending_clan_xiexuan: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["wending_jidu", "wending_bingzhu", "clanshuze"],
	},
	wending_clan_xielingyun: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["wending_beixuan", "wending_guiwu", "clanshuze"],
	},
	wending_clan_xieshi: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["wending_suijian", "clanshuze"],
	},
	qunyou_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_longjue", "qunyou_yiyong"],
	},
	qunyou_sunshao: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_dingyi", "qunyou_zhichao"],
	},
	qunyou_caocao: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_muxin", "qunyou_cangxiao"],
	},
	qunyou_sp_wenyang: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_lingzhen", "qunyou_lingzhen2"],
	},
	qunyou_liukun: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_hunsui", "qunyou_cairuo"],
	},
	qunyou_simayi: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_dusheng"],
	},
	qunyou_sunjiao: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_fenzi"],
	},
	qunyou_v_luxun: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_yiling", "qunyou_yiye", "qunyou_bingde"],
	},
	qunyou_caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_chouci", "qunyou_qionfu"],
	},
	qunyou_haopu: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_jicheng"],
	},
	qunyou_chen_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zhaduo", "qunyou_danpo"],
	},
	qunyou_wanglang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_gushe", "qunyou_zuobao"],
	},
	qunyou_cbp_zhaoyun: {
        sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 5,
		hujia: 0,
		skills: ["qunyou_xianzhan", "qunyou_zhouxuan", "qunyou_gudan"],
	},
	qunyou_jiangwei: {
        sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_xiongbo", "qunyou_jingfa"],
	},
	qunyou_sb_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_zhongyan", "qunyou_wanlan", "qunyou_xutian"],
	},
	qunyou_pengyue: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_shenshi", "qunyou_jianjiang"],
	},
	qunyou_liumo: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_tongxian"],
	},
	qunyou_meng_liufeng: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_aoyue", "qunyou_junming", "qunyou_xingshi"],
	},
	qunyou_caoshuang: {
        sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zhihu", "qunyou_weitai"],
	},
	qunyou_hanshiwuhu: {
		sex: "male",
		group: "wei",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["qunyou_luzhan","qunyou_mangzhan"],
	},
	qunyou_sb_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_quanmou", "qunyou_huameng", "qunyou_zhashu"],
	},
	qunyou_yang_wang: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_zhouli", "qunyou_yunxian"],
	},
	qunyou_caoxiancaohua: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_lingyu","qunyou_qingmeng"],
	},
	qunyou_mo_jiangwei: {
		sex: "male",
		group: "devil",
		hp: 4,
		maxHp: 9,
		hujia: 0,
		skills: ["qunyou_zhuoqu", "qunyou_guwo", "qunyou_chubu"],
	},
	qunyou_sb_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_jingce"],
	},
	qunyou_clan_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["太原王氏"],
		skills: ["qunyou_pianyi", "qunyou_cuiping", "clanzhongliu"],
	},
	qunyou_wu_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zisheng", "qunyou_xianlue", "qunyou_haoxian"],
	},
	qunyou_v_guanyu: {
        sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_wuwei", "qunyou_zhenxiang"],
	},
	qunyou_xx_sunce: {
		sex: "male",
		group: "wu",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["qunyou_sc1_guanyong","qunyou_sc1_pingzheng"],
	},
	qunyou_zhangyan: {
        sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_qingjie","qunyou_zhoujie"],
	},
	shanhe_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["shanhe_chuandao","shanhe_muzhong"],
	},
	shanhe_hanfu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["shanhe_zhongzhe", "shanhe_jueliang"],
	},
	shanhe_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["shanhe_taolue", "shanhe_hezong"],
	},
	shanhe_luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 6,
		hujia: 0,
		skills: ["shanhe_zhenpan","shanhe_kangbian","shanhe_yinshan"],
	},
	qunyou_lvlingqi:{
		sex: "female",
	    group: "qun",
		hp: 5,
		maxHp: 5,
		hujia: 0, 
		skills: ["qunyou_qiwu","qunyou_qinzhan"],
	},
    shanhe_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 5,
		maxHp: 5,
		hujia: 0,  
		skills: ["shanhe_yongli","shanhe_taoning","shanhe_fuzhu"],
	},
	qunyou_lvyi: {
		sex: "male",
	    group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0, 
		skills: ["qunyou_gouxian","qunyou_zhongshi"],
	},
	yachaiclan_cuiyan:{
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,  
		clans: ["清河崔氏"],
		skills: ["yachai_jianshi","yachai_shibian","clanlunyi"],
	},
	yachaiclan_wangxiang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,  
		clans: ["琅琊王氏"],
		skills: ["yachai_qingjie","yachai_chenxun","clanqianzhang"],
	},
	yachaiclan_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["太原王氏"],
		skills: ["yachai_qianjiao", "yachai_anchao", "clanzhongliu"],
	},
	yachaiclan_wuyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,  
		clans: ["陈留吴氏"],
		skills: ["yachai_yijiang","yachai_jieren","clanmuyin"],
	},
	yachaiclan_xunyu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,  
		clans: ["颍川荀氏"],
		skills: ["yachai_jizi","yachai_tuicheng","yachai_yingxiang","clandaojie"],
	},
	yachaiclan_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_lijian","yachai_tanghuo","clanxunli"],
	},
	yachaiclan_lukang: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_bozui","yachai_heshu","clanxunli"],
	},
	yachaiclan_luji2: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_bianwang","yachai_najian","clanxunli"],
	},
	yachaiclan_luyun: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_wuyan","yachai_lihui","clanxunli"],
	},
	yachaiclan_luji: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_shangwen","yachai_gailan","clanxunli"],
	},
	yachaiclan_luyusheng: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_yishuang","yachai_baizhou","clanxunli"],
	},
	yachaiclan_lukai: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_jingui","yachai_jiegai","clanxunli"],
	},
	yachaiclan_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_shice","yachai_jiangming","clanzhuding"],
	},
	yachaiclan_zhugezhan: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_yanling","yachai_feijiao","clanzhuding"],
	},
	yachaiclan_zhugeshang: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_xiaoqiang","yachai_changshang","clanzhuding"],
	},
	yachaiclan_zhugejin: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_xiumu","yachai_shenjiao","clanzhuding"],
	},
	yachaiclan_zhugeke: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_qiyi","yachai_chengshi","clanzhuding"],
	},
	yachaiclan_zhugedan: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_jinshi","yachai_faji","clanzhuding"],
	},
	yachaiclan_zhugeliang2: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_liuliu","clanzhuding"],
	},
	qunyou_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_xiongzi"],
	},
	qunyou_panjun:{
		sex:"male",
		group:"wu",
		hp:3,
		maxHp:3,
		hujia:0,
		skills:["qunyou_guanwei","qunyou_gongqing"],
	},
	qunyou_wangyun: {
        sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_lianchou", "qunyou_yuannan", "qunyou_huiqing"],
	},
	qunyou_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_mingce", "qunyou_dinglue"],
	},
	qunyou_zhaoshuang: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_fangyuan", "qunyou_xianlv", "qunyou_jingkuo"],
	},
	qunyou_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_wusheng"],
	},
	zishu_liyan: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_duliang", "zishu_xiaqing"],
	},
	zishu_lvju: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zishu_nilang"],
	},
	zishu_xunyu: {
		sex: "male",
		group: "han",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["颍川荀氏"],
		skills: ["zishu_kongxin", "zishu_shangzhao", "clandaojie"],
	},
	zishu_wangguan: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zishu_mitu", "zishu_jinlu"],
	},
	zishu_sunhe: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_jiaoxi", "zishu_gongshang"],
	},
	zhuoming_feili_gongsunyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhuoming_feili", "zhuoming_weigong"],
	},
	zhuoming_gongsunyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhuoming_fengpan", "zhuoming_fuluan", "zhuoming_quantong"],
	},
	zhuoming_liuyan: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhuoming_liezong"],
	},
	zishu_zhangjinyun: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_yusan", "zishu_huifen"],
	},
	xiaobai_lizhaoyi: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_zhiwen", "xiaobai_minnian", "xiaobai_jufen"],
	},
	qunyou_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_shishi","qunyou_jiji"],
	},
	qunyou_clan_zhugejun: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["qunyou_gengdu","clanzuguan"],
	},
	qiufeng_zhangqiying: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiufeng_liugong","qiufeng_sanqing"],
	},
	qiufeng_hushi: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiufeng_jisi", "qiufeng_fuyao"],
	},
	zishu_panshu: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_zhilian","zishu_chousu"],
	},
	qunyou_taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zhanwei","qunyou_dangzhen"],
	},
	qunyou_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_jiang", "qunyou_yingpo"],
	},
	qunyou_guotu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_qushi","qunyou_shiwei"],
	},
	qunyou_liuchen: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_daolie"],
	},
	qunyou_masu:{
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_qilue"],
	},
	threed_dongbai:{
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["threed_cat_eye","threed_xiang_e","threed_zhi_luan"],
	},
	threed_heji:{
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["threed_xuyi1","threed_xuyi2"],
	},
	threed_qianzhao:{
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["threed_yuanzhen","threed_zhiyong"],
	},
	shanhe_jiangwei:{
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["shanhe_yuanzhi","shanhe_shutu"],
	},
	shanhe_wangyi:{
		sex: "female",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["shanhe_zijiu","shanhe_huoyu"],
	},
	xiaobai_lite:{
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_julan","xiaobai_kuotao"],
	},
	xiaobai_suojing:{
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_danzhi","xiaobai_zhoubi"],
	},
	zishu_zangba: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zishu_jifan"],
	},
	zishu_duanjiong: {
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zishu_guomie", "zishu_haixiang"],
	},
	zishu_shantao: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_buqun", "zishu_bugu"],
	},
	qiufeng_xiahouhui: {
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiufeng_xixin", "qiufeng_paoshi"],
	},
	zishu_maohuanghou: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_shichong","zishu_panjun","zishu_chuyan"],
	},
	zishu_guli: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zishu_henglan", "zishu_jibi"],
	},
	zhuoming_mateng:{
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhuoming_tasai","zhuoming_juanlong"],
	},
	zhuoming_fq_mateng:{
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhuoming_fengqi"],
	},
	zhuoming_sc_mateng:{
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhuoming_hengchi", "zhuoming_shuocheng"],
	},
	xuandie_xunguan: {
		sex: "female",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["颍川荀氏"],
		skills: ["xuandie_yuwei"],
	},
	xuandie_lvzhi: {
		sex: "female",
		group: "han",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xuandie_junce"],
	},
	xuandie_wenjun: {
		sex: "female",
		group: "han",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xuandie_xiangfu", "xuandie_yixin"],
	},
	xuandie_zuti: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xuandie_jiji"],
	},
	qunyou_zhongjin: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_shushou"],
	},
	qunyou_feiyi: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_huaisui", "qunyou_yangxi"],
	},
	qunyou_clan_xunzhuan: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["颍川荀氏"],
		skills: ["qunyou_lingzhi", "qunyou_chengzhi", "clandaojie"],
	},
	qunyou_clan_wangrong: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊王氏"],
		skills: ["qunyou_shili","qunyou_huimo","clanqianzhang"],
	},
	qunyou_clan_yuantanshang: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["汝南袁氏"],
		skills: ["qunyou_liaofa", "qunyou_xiqiang", "qunyou_yaobing", "clanguming"],
	},
	qunyou_clan_yuanshao:{
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["汝南袁氏"],
		skills: ["qunyou_hezhong", "qunyou_shenli", "clanguming"],
	},
	zishu_yongkai: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zishu_jiaoxie","zishu_jieshuo"],
	},
	qunyou_yangqun: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_chitu","qunyou_tiaolong"],
	},

	qunyou_clan_yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["汝南袁氏"],
		skills: ["qunyou_quanwang", "qunyou_daimang", "clanguming"],
	},

	maokuo_caobuxing: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["maokuo_luomo", "maokuo_xiaoxing"],
	},

	maokuo_jiangwei: {
		sex: "male",
		group: "shen",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["maokuo_xuezheng", "maokuo_juezhi"],
	},

	maokuo_nuqi_jiangwei: {
		sex: "male",
		group: "shen",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["maokuo_zhanhao", "maokuo_simen", "maokuo_xuejian"],
	},

	maokuo_pengyang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["maokuo_kunguan", "maokuo_xinyi"],
	},

	maokuo_wangwang: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["maokuo_xinwang", "maokuo_xiangxie"],
	},

	qunyou_clan_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["天水姜氏"],
		skills: ["qunyou_zhuhui","qunyou_juelan", "clan_xinggu"],
	},

	zishu_liangxi: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zishu_yuanjiang", "zishu_suqi"],
	},

	qunyou_clan_diaochan2: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["太原王氏"],
		skills: ["qunyou_huoni", "clanzhongliu"],
	},

	xiaobai_hufang: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_liewu", "xiaobai_chongjuan"],
	},

	xiaobai_lvzhu: {
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_huzhen", "xiaobai_liufang"],
	},

	xiaobai_malun: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_bianmei", "xiaobai_yingying"],
	},

	qunyou_taokan: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_donglan"],
	},

	qunyou_clan_kongyu: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["鲁国孔氏"],
		skills: ["qunyou_guchou", "qunyou_jipo", "clan_guoting"],
	},

	xiaobai_zhaoshuang: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_hengxian", "xiaobai_zhuyuan"],
	},

	xiaobai_shenmu: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_sanfa", "xiaobai_shidao", "xiaobai_dengxian"],
	},

	qunyou_clan_yuankui: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["汝南袁氏"],
		skills: ["qunyou_touxie", "qunyou_yinshen", "clanguming"],
	},

	xiaobai_gaoding: {
		sex: "male",
		group: "qun",
		doubleGroup: ["qun", "shu"],
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_pantan", "xiaobai_manyi"],
	},

	zhuoming_dongzhuo: {
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhuoming_tingfeng", "zhuoming_gongyan"],
	},

	qunyou_jiananfeng: {
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_jike"],
	},

	qunyou_sunhao: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_lanshe", "qunyou_funve", "qunyou_fushui"],
	},

	xingyu_sunshangxiang: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xingyu_yingfeng", "xingyu_haowu"],
	},

	qunyou_clan_wangjun: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["太原王氏"],
		skills: ["qunyou_yinhu", "clanzhongliu"],
	},

	shanhe_maliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["shanhe_zhishu", "shanhe_hexi"],
	},

	qunyou_zhugeguo: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_qirang", "qunyou_shuzuo"],
	},

	xiaobai_liusong: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_buxi", "xiaobai_zhenlv"],
	},

	xiaobai_zhangjian: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_changhe", "xiaobai_jiudian", "xiaobai_shilang"],
	},

	xiaobai_shenyi: {
		sex: "male",
		group: "wei",
		doubleGroup: ["wei", "shu"],
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_beibian", "xiaobai_nisi"],
	},

	xiaobai_baoxun: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_gengjian", "xiaobai_bingyan"],
	},

	xiaobai_chengxi: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_zuangong", "xiaobai_beisi"],
	},

	xiaobai_xunyue: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_boyi"],
	},

	xiaobai_feishi: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_cuanhe", "xiaobai_anzuo"],
	},

	xiaobai_hanji: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_junjin", "xiaobai_anmang"],
	},

	xiaobai_youchu: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_chengmo", "xiaobai_jingyi"],
	},

	xiaobai_lvyi: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_jixun", "xiaobai_danggou"],
	},

	xiaobai_fugu: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_yujie", "xiaobai_cetu"],
	},

	xiaobai_lisheng: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_tanxu", "xiaobai_danglian"],
	},

	xiaobai_lisheng: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_danglian", "xiaobai_tanxu"],
	},

	xiaobai_tianxu: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_cairen", "xiaobai_shiqi"],
	},

	xiaobai_zhushixing: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_qiudao", "xiaobai_chuanjing"],
	},

	xiaobai_xuci: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_huisu", "xiaobai_boshe"],
	},

	xiaobai_dinggu: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_chenzhu", "xiaobai_lvjie"],
	},

	xiaobai_zhugerong: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_xingzu", "xiaobai_bowen"],
	},

	xiaobai_cuifu: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_nichang", "xiaobai_diaodie"],
	},

	xiaobai_hushi: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_huoyan", "xiaobai_yanzai"],
	},

	xiaobai_jiyan: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_gaiju", "xiaobai_suli"],
	},

	xiaobai_yangxianrong: {
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_tucun", "xiaobai_xingluan", "dualside"],
		dualSideCharacter: "xiaobai_yangxianrong_hidden",
	},

	xiaobai_yangxianrong_hidden: {
		sex: "female",
		group: "jin",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		skills: ["xiaobai_tucun", "xiaobai_xingluan", "dualside"],
		dualSideCharacter: "xiaobai_yangxianrong",
		isUnseen: true,
	},

	xiaobai_zhaoqi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_quanyi", "xiaobai_chenguang"],
	},

	xiaobai_zhaorao: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_bizhao", "xiaobai_quanqing", "xiaobai_shanzi"],
	},

	xiaobai_heyong: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_anmou", "xiaobai_shipin"],
	},

	xiaobai_liuhongx: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_bozhu", "xiaobai_qianxiang"],
	},

	xiaobai_liukun: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_huailie", "xiaobai_beijia"],
	},

	xiaobai_liuying: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_jinwei"],
	},

	xiaobai_liuji: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_meijian", "xiaobai_yongchong"],
	},

	xiaobai_liumin: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_yizuo", "xiaobai_lianzhi"],
	},

	xiaobai_lifeng: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_danming", "xiaobai_youbai"],
	},

	xiaobai_luyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_jinti", "xiaobai_lincai"],
	},

	xiaobai_weidan: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_jinmo", "xiaobai_yinhan"],
	},

	xiaobai_yangyong: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_youjian", "xiaobai_zhongxi"],
	},

	xiaobai_dengfuren: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_dianchi", "xiaobai_xiancu", "xiaobai_quanxi"],
	},

	xiaobai_louxuan: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_linji", "xiaobai_lvgu"],
	},

	xiaobai_maohuanghou: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_nianxing", "xiaobai_rongai"],
	},

	xiaobai_wangsi: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_fuqing", "xiaobai_qinrong"],
	},

	xiaobai_sunshao: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_leicheng", "xiaobai_liehe"],
	},

	xiaobai_baochu: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_ziren", "xiaobai_renxie"],
	},

	xiaobai_huzhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_qietian", "xiaobai_qieshou"],
	},

	xiaobai_wangbi: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_zhini", "xiaobai_yangying"],
	},

	xiaobai_xumu: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_xiaohuang", "xiaobai_shegeng"],
	},

	xiaobai_huzong: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_mozhuan", "xiaobai_zuocui"],
	},

	xiaobai_zhaozi: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_fulun", "xiaobai_tongyan"],
	},

	xiaobai_huangwan: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_weidang", "xiaobai_zhenggu"],
	},

	xiaobai_gaixun: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_zhenglie", "xiaobai_suye"],
	},

	xiaobai_fuxuan: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_shujian", "xiaobai_gangzao"],
	},

	xiaobai_simayue: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_zhuanfeng", "xiaobai_huailan"],
	},

	xiaobai_wangbimawen: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_guajie", "xiaobai_yaozheng"],
	},

	xiaobai_weiji: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_dianyi", "xiaobai_yishi"],
	},

	xiaobai_fanjian: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_qingjie", "xiaobai_weishi"],
	},

	xiaobai_hezhi: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_shendian", "xiaobai_ziyi"],
	},

	xiaobai_lujix: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_kanwu", "xiaobai_zhuanshu"],
	},

	xiaobai_doumiao: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_weijiu", "xiaobai_duobi"],
	},

	xiaobai_hexiu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_gushou", "xiaobai_xuanbian"],
	},

	xiaobai_huangfugui: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_zhanwei", "xiaobai_shubian"],
	},

	xiaobai_yangxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_guanli", "xiaobai_xuanyu"],
	},

	xiaobai_shichong: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_xuanfu", "xiaobai_jingu"],
	},

	xiaobai_nieyou: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_zhuizhu", "xiaobai_xunlu"],
	},

	xiaobai_xueying: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_zhuanyu", "xiaobai_guancheng"],
	},

	xiaobai_douwu: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_zouchu", "xiaobai_fuguo"],
	},

	xiaobai_liying: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_zhuwei", "xiaobai_zhenyi"],
	},

	xiaobai_wangxiu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_wangxiu_ziyi", "xiaobai_daozhu"],
	},

	xiaobai_leguang: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_piyun", "xiaobai_xiaoxin"],
	},

	xiaobai_peikai: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_liuyu", "xiaobai_supian"],
	},

	xiaobai_peiwei: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_kenyan", "xiaobai_liangzhong"],
	},

	xiaobai_zhangfang: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_luedu", "xiaobai_wange"],
	},

	xiaobai_guopu: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_xunlong", "xiaobai_pingfeng"],
	},

	xiaobai_simayou: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_qianren", "xiaobai_xincheng"],
	},

	xiaobai_simajun: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_diefeng", "xiaobai_tianfa"],
	},

	xiaobai_wangjunx: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_jiuzheng", "xiaobai_liguang"],
	},

	xiaobai_jishao: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_xuehan", "xiaobai_angran"],
	},

	xiaobai_zuosi: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_yongshi1", "xiaobai_lanfu"],
	},

	xiaobai_heqiao: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_yushi", "xiaobai_gangjiao"],
	},

	xiaobai_zhaoyu: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_huihao", "xiaobai_weilv"],
	},

	xiaobai_zhangyu: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_xiongchen", "xiaobai_yanhuo"],
	},

	xiaobai_xiyingxi: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_duanhuo", "xiaobai_nirao"],
	},

	qunyou_mo_wangyun: {
		sex: "male",
		group: "devil",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_jinfa", "qunyou_ranchen"],
	},

	xiaobai_xunkai: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_huqu", "xiaobai_yifa"],
	},

	xiaobai_luoshang: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_xuancheng", "xiaobai_shashi"],
	},

	qunyou_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["qunyou_chouwo", "qunyou_dushi"],
	},

	qunyou_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["颍川钟氏"],
		skills: ["qunyou_yewang", "qunyou_zhuting", "qunyou_yuyuan", "qunyou_quyan"],
	},

	maokuo_zhangte: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["maokuo_shidi"],
	},

	qunyou_sunziliufang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_zhigong", "qunyou_fuan"],
	},

	qunyou_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_hedan", "qunyou_weishi"],
	},
};