/**
 * 武将基础数据
 * 立绘：extension/群友设计/image/character/{武将id}.jpg（由 patchCharacterAssets 自动写入 img）
 */
export const characterData = {
	qunyou_wenyang: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_youlong", "qunyou_fuzhen"],
	},
	qunyou_shibao: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_cuisheng"],
	},
	qunyou_sunxiu: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_rongguo"],
	},
	qunyou_xiedaoyun: {
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_yongxu", "qunyou_miaoyu", "qunyou_shuze"],
	},
	qunyou_xiean: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_yanghui", "qunyou_yaliang", "qunyou_shuze"],
	},
	qunyou_xiexuan: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_jidu", "qunyou_bingzhu", "qunyou_shuze"],
	},
	qunyou_xielingyun: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_beixuan", "qunyou_guiwu", "qunyou_shuze"],
	},
	qunyou_xieshi: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_suijian", "qunyou_shuze"],
	},
	qunyou_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_longjue", "qunyou_yiyong"],
	},
	qunyou_sunshao: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_dingyi", "qunyou_zhichao"],
	},
	qunyou_caocao: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_muxin", "qunyou_cangxiao"],
	},
	qunyou_sp_wenyang: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_lingzhen", "qunyou_lingzhen2"],
	},
	qunyou_liukun: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_hunsui", "qunyou_cairuo"],
	},
	qunyou_simayi: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_dusheng"],
	},
	qunyou_sunjiao: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_fenzi"],
	},
	qunyou_luxun: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_yiling", "qunyou_yiye", "qunyou_bingde"],
	},
	qunyou_caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_chouci", "qunyou_qionfu"],
	},
	qunyou_haopu: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_jicheng"],
	},
	qunyou_chen_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zhaduo", "qunyou_danpo"],
	},
	qunyou_wanglang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_gushe", "qunyou_zuobao"],
	},
	qunyou_cbp_zhaoyun: {
        sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 5,
		hujia: 0,
		skills: ["qunyou_xianzhan", "qunyou_zhouxuan", "qunyou_gudan"],
	},
	qunyou_jiangwei: {
        sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_xiongbo", "qunyou_jinfa"],
	},
	qunyou_sb_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_zhongyan", "qunyou_wanlan", "qunyou_xutian"],
	},
	qunyou_pengyue: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_shenshi", "qunyou_jianjiang"],
	},
	qunyou_liumo: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_tongxian"],
	},
	qunyou_meng_liufeng: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_aoyue", "qunyou_junming", "qunyou_xingshi"],
	},
	qunyou_caoshuang: {
        sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zhihu", "qunyou_weitai"],
	},
	qunyou_hanshiwuhu: {
		sex: "male",
		group: "wei",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["qunyou_luzhan","qunyou_mangzhan"],
	},
	qunyou_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_quanmou", "qunyou_huameng", "qunyou_zhashu"],
	},
	qunyou_yang_wang: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_zhouli", "qunyou_yunxian"],
	},
	qunyou_caoxiancaohua: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_lingyu","qunyou_qingmeng"],
	},
	qunyou_mo_jiangwei: {
		sex: "male",
		group: "devil",
		hp: 4,
		maxHp: 9,
		hujia: 0,
		skills: ["qunyou_zhuoqu", "qunyou_guwo", "qunyou_chubu"],
	},
	qunyou_sb_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_jingce"],
	},
	qunyou_clan_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["太原王氏"],
		skills: ["qunyou_pianyi", "qunyou_cuiping", "clanzhongliu"],
	},
	qunyou_wu_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zisheng", "qunyou_xianlue", "qunyou_haoxian"],
	},
	qunyou_v_guanyu: {
        sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_wuwei", "qunyou_zhenxiang"],
	},
	qunyou_xx_sunce: {
		sex: "male",
		group: "wu",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["qunyou_sc1_guanyong","qunyou_sc1_pingzheng"],
	},
	qunyou_zhangyan: {
        sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_qingjie","qunyou_zhoujie"],
	},
	shanhe_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["shanhe_chuandao","shanhe_muzhong"],
	},
	shanhe_hanfu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["shanhe_zhongzhe", "shanhe_jueliang"],
	},
	shanhe_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["shanhe_taolue", "shanhe_hezong"],
	},
	shanhe_luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 6,
		hujia: 0,
		skills: ["shanhe_zhenpan","shanhe_kangbian","shanhe_yinshan"],
	},
	qunyou_lvlingqi:{
		sex: "female",
	    group: "qun",
		hp: 5,
		maxHp: 5,
		hujia: 0, 
		skills: ["qunyou_qiwu","qunyou_qinzhan"],
	},
    shanhe_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 5,
		maxHp: 5,
		hujia: 0,  
		skills: ["qunyou_yongli","shanhe_taoning","shanhe_fuzhu"],
	},
	qunyou_lvyi: {
		sex: "male",
	    group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0, 
		skills: ["qunyou_gouxian","qunyou_zhongshi"],
	},
	yachaiclan_cuiyan:{
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,  
		clans: ["清河崔氏"],
		skills: ["yachai_jianshi","yachai_shibian","clanlunyi"],
	},
	yachaiclan_wangxiang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,  
		clans: ["琅琊王氏"],
		skills: ["yachai_qingjie","yachai_chenxun","clanqianzhang"],
	},
	yachaiclan_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["太原王氏"],
		skills: ["yachai_qianjiao", "yachai_anchao", "clanzhongliu"],
	},
	yachaiclan_wuyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,  
		clans: ["陈留吴氏"],
		skills: ["yachai_yijiang","yachai_jieren","clanmuyin"],
	},
	yachaiclan_xunyu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,  
		clans: ["颍川荀氏"],
		skills: ["yachai_jizi","yachai_tuicheng","yachai_yingxiang","clandaojie"],
	},
	yachaiclan_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_lijian","yachai_tanghuo","clanxunli"],
	},
	yachaiclan_lukang: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_bozui","yachai_heshu","clanxunli"],
	},
	yachaiclan_luji2: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_bianwang","yachai_najian","clanxunli"],
	},
	yachaiclan_luyun: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_wuyan","yachai_lihui","clanxunli"],
	},
	yachaiclan_luji: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_shangwen","yachai_gailan","clanxunli"],
	},
	yachaiclan_luyusheng: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_yishuang","yachai_baizhou","clanxunli"],
	},
	yachaiclan_lukai: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["吴郡陆氏"],
		skills: ["yachai_jingui","yachai_jiegai","clanxunli"],
	},
	yachaiclan_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_shice","yachai_jiangming","clanzhuding"],
	},
	yachaiclan_zhugezhan: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_yanling","yachai_feijiao","clanzhuding"],
	},
	yachaiclan_zhugeshang: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_xiaoqiang","yachai_changshang","clanzhuding"],
	},
	yachaiclan_zhugejin: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_xiumu","yachai_shenjiao","clanzhuding"],
	},
	yachaiclan_zhugeke: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_qiyi","yachai_chengshi","clanzhuding"],
	},
	yachaiclan_zhugedan: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_jinshi","yachai_faji","clanzhuding"],
	},
	yachaiclan_zhugeliang2: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["yachai_liuliu","clanzhuding"],
	},
	qunyou_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_xiongzi"],
	},
	qunyou_panjun:{
		sex:"male",
		group:"wu",
		hp:3,
		maxHp:3,
		hujia:0,
		skills:["qunyou_guanwei","qunyou_gongqing"],
	},
	qunyou_wangyun: {
        sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_lianchou", "qunyou_yuannan", "qunyou_huiqing"],
	},
	zishu_liyan: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_duliang", "zishu_xiaqing"],
	},
	zishu_lvju: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zishu_nilang"],
	},
	zishu_xunyu: {
		sex: "male",
		group: "han",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["颍川荀氏"],
		skills: ["zishu_kongxin", "zishu_shangzhao", "clandaojie"],
	},
	zishu_wangguan: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zishu_mitu", "zishu_jinlu"],
	},
	zishu_sunhe: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_jiaoxi", "zishu_gongshang"],
	},
	zhuoming_feili_gongsunyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhuoming_feili", "zhuoming_weigong"],
	},
	zhuoming_gongsunyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhuoming_fengpan", "zhuoming_fuluan", "zhuoming_quantong"],
	},
	zhuoming_liuyan: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhuoming_liezong"],
	},
	zishu_zhangjinyun: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_yusan", "zishu_huifen"],
	},
	xiaobai_lizhaoyi: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_zhiwen", "xiaobai_minnian", "xiaobai_jufen"],
	},
	qunyou_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_shishi","qunyou_jiji"],
	},
	qunyou_clan_zhugejun: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["琅琊诸葛氏"],
		skills: ["qunyou_gengdu","clanzuguan"],
	},
	qiufeng_zhangqiying: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiufeng_liugong","qiufeng_sanqing"],
	},
	qiufeng_hushi: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiufeng_jisi", "qiufeng_fuyao"],
	},
	zishu_panshu: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zishu_zhilian","zishu_chousu"],
	},
	qunyou_taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zhanwei","qunyou_dangzhen"],
	},
	qunyou_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_jiang", "qunyou_yingpo"],
	},
	qunyou_guotu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_qushi","qunyou_shiwei"],
	},
	qunyou_liuchen: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_daolie"],
	},
	qunyou_masu:{
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_qilue"],
	},
	threed_dongbai:{
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["threed_cat_eye","threed_xiang_e","threed_zhi_luan"],
	},
	threed_heji:{
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["threed_xuyi1","threed_xuyi2"],
	},
	shanhe_jiangwei:{
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["shanhe_yuanzhi","shanhe_shutu"],
	},
	shanhe_wangyi:{
		sex: "female",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["shanhe_zijiu","shanhe_huoyu"],
	},
	xiaobai_lite:{
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xiaobai_julan","xiaobai_kuotao"],
	},
	xiaobai_suojing:{
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiaobai_danzhi","xiaobai_zhoubi"],
	},
};
