/**
 * 武将基础数据
 * 立绘：extension/群友设计/image/character/{武将id}.jpg（由 patchCharacterAssets 自动写入 img）
 */
export const characterData = {
	qunyou_wenyang: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_youlong", "qunyou_fuzhen"],
	},
	qunyou_shibao: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_cuisheng"],
	},
	qunyou_sunxiu: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_rongguo"],
	},
	qunyou_xiedaoyun: {
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_yongxu", "qunyou_miaoyu", "qunyou_shuze"],
	},
	qunyou_xiean: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_yanghui", "qunyou_yaliang", "qunyou_shuze"],
	},
	qunyou_xiexuan: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_jidu", "qunyou_bingzhu", "qunyou_shuze"],
	},
	qunyou_xielingyun: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_beixuan", "qunyou_guiwu", "qunyou_shuze"],
	},
	qunyou_xieshi: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		clans: ["陈郡谢氏"],
		skills: ["qunyou_suijian", "qunyou_shuze"],
	},
	qunyou_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_longjue", "qunyou_yiyong"],
	},
	qunyou_sunshao: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_dingyi", "qunyou_zhichao"],
	},
	qunyou_caocao: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_muxin", "qunyou_cangxiao"],
	},
	qunyou_spwenyang: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_lingzhen", "qunyou_lingzhen2"],
	},
	qunyou_liukun: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_hunsui", "qunyou_cairuo"],
	},
	qunyou_simayi: {
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_dusheng"],
	},
	qunyou_sunjiao: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_fenzi"],
	},
	qunyou_luxun: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_yiling", "qunyou_yiye", "qunyou_bingde"],
	},
	qunyou_caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_chouci", "qunyou_qionfu"],
	},
	qunyou_haopu: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_jicheng"],
	},
	qunyou_chenzhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zhaduo", "qunyou_danpo"],
	},
	qunyou_wanglang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_gushe", "qunyou_zuobao"],
	},
	qunyou_cbpzhaoyun: {
        sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_xianzhan", "qunyou_zhouxuan", "qunyou_gudan"],
	},
	qunyou_jiangwei: {
        sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_xiongbo", "qunyou_jinfa"],
	},
	qunyou_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_zhitian", "qunyou_zhijue"],
	},
	qunyou_pengyue: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_shenshi", "qunyou_jianjiang"],
	},
	qunyou_liumo: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_tongxian"],
	},
	qunyou_mengliufeng: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_aoyue", "qunyou_junming", "qunyou_xingshi"],
	},
	qunyou_caoshuang: {
        sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zhihu", "qunyou_weitai"],
	},
	qunyou_hanshiwuhu: {
		sex: "male",
		group: "wei",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["qunyou_luzhan"],
	},
	qunyou_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_quanmou", "qunyou_huameng", "qunyou_zhashu"],
	},
	qunyou_yang_wang: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_zhouli", "qunyou_yunxian"],
	},
	qunyou_xian_hua: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_lingyu","qunyou_qingmeng"],
	},
	qunyou_mojiangwei: {
		sex: "male",
		group: "devil",
		hp: 4,
		maxHp: 9,
		hujia: 0,
		skills: ["qunyou_zhuoqu", "qunyou_guwo", "qunyou_chubu"],
	},
	qunyou_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_jingce"],
	},
	qunyou_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		clans: ["太原王氏"],
		skills: ["qunyou_pianyi", "qunyou_cuiping", "clanzhongliu"],
	},
	qunyou_wuzhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_zisheng", "qunyou_xianlue", "qunyou_haoxian"],
	},
	qunyou_weiguanyu: {
        sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_taowei", "qunyou_hanguo"],
	},
	qunyou_sunce: {
		sex: "male",
		group: "wu",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["qunyou_sc1_guanyong","qunyou_sc1_pingzheng"],
	},
	qunyou_zhangyan: {
        sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qunyou_qingjie","qunyou_zhoujie"],
	},
	shanhe_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qunyou_chuandao","qunyou_muzhong"],
	},
	shanhe_luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 6,
		hujia: 0,
		skills: ["qunyou_zhenpan","qunyou_kangbian","qunyou_yinshan"],
	},
	qunyou_lvlingqi:{
		sex: "female",
	  group: "qun",
		hp: 5,
		maxHp: 5,
		hujia: 0, 
		skills: ["qunyou_qiwu","qunyou_qinzhan"],
	},
  shanhe_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 5,
		maxHp: 5,
		hujia: 0,  
		skills: ["qunyou_yongli","qunyou_taoning","qunyou_fuzhu"],
	},
};
