/** 武将 designer / 简介 characterIntro */
export const characterIntro = {
	qunyou_wenyang: "设计：pioneer",
	qunyou_shibao: "设计：滑溜溜。<br>评价：什么时候铁锁，什么时候戮力，都是要考虑的问题，用不好容易资敌，还容易烧到自己。",
	qunyou_sunxiu: "设计：？。<br>",
	qunyou_xiedaoyun: "设计：元徒。<br>评价：需要攒牌，否则就没牌印无懈和触发响应，但是在敌方连续使用锦囊时，一旦滚起来，就非常恐怖了，无懈需要的底牌越来越少，手上的牌越来越多，属于才女的应对自如十分有画面感。",
	qunyou_xiean: "设计：夏商周在。<br>陈郡谢氏中最强的，族谢安的公式打法就是，延后摸3牌，之后的摸牌都不延后->遇到弃牌就延后->用一张伤害牌，然后摸三弃三捡回这张伤害牌。",
	qunyou_xiexuan: "设计：拉普拉斯。<br>评价：有点弱了，印杀和桃的条件太苛刻，况且横置角色的条件也很难，如果把兵主不限次数，强度就正常了。",
	qunyou_zhaoyun: "设计：钟林。<br>评价：又有强度但也不至于太阴的设计。",
	qunyou_sunshao: "设计：（B站）叼五我爱你麻。<br>评价：实际上非常缺装备牌，当然，过牌量不错。",
	qunyou_caocao: "设计：钟林。<br>主要是单机，真正玩的时候需要放宽点条件，比如选择获得大于展示牌点数的牌，或者对小于展示牌点数的角色造成伤害，最后回复等于点数牌的体力。",
    qunyou_xielingyun: "设计：混乱的啃",
	qunyou_xieshi: "设计：ff",
	qunyou_spwenyang: "设计：昆世",
	qunyou_liukun: "欢愉与希望<br>“何意百炼刚，化为绕指柔。”",
	qunyou_sunjiao: "设计：杰劼夫长(贴吧）",
	qunyou_luxun: "设计：鬼才李华（b站）",
	qunyou_caozhi: "设计：钟林",
	qunyou_simayi: "设计：迟眠饱（B站）<br>，来自BV1vk5G6AERQ。评价：挺看运气的，强度阳顶天",
	qunyou_haopu: "设计：yyuan",
	qunyou_chenzhaoyun: "设计：0^0。<br>评价：挺好的设计，印牌很强",
	qunyou_wanglang: "设计：滑溜溜。<br>评价：阴完了，拿到A和K就能空城全场",
	qunyou_cbpzhaoyun: "设计：琉多斯。<br>评价：区？？",
	qunyou_jiangwei: "来源：BV1CDGv6uESF<br>吐槽：原版那描述都能自创好几个新概念了，还有，太弱了，共同拼点本来就不容易赢，自身顶多是小制衡，没有手牌还发动不了技能",
	qunyou_zhugeliang: "设计：寻辉逐烨<br>吐槽：太麻烦了，需要改进",
	qunyou_pengyue: "设计：鹭。<br>评价：",
	qunyou_liumo: "设计：祂不想。<br>评价：十分好玩的设计，伪用一摸一，爽！",
	qunyou_mengliufeng: "设计：未知。<br>评价：拿一点体力上限换两张决斗。额，不好衡量",
	qunyou_caoshuang: "设计：嘻˘꒳˘羲",
	qunyou_hanshiwuhu: "设计：佐世保之时雨。<br>评价：",
	qunyou_zhonghui: "设计：熏鱼不爱果子。修改：欢愉与希望<br>评价：我也不知道我改的好不好，总之比原版强了。",
	qunyou_yang_wang: "设计：西夏笠谷。<br>评价：",
};
