/** 武将 designer / 简介 characterIntro */
export const characterIntro = {
	qunyou_wenyang: "设计：pioneer",
	qunyou_shibao: "设计：滑溜溜。<br>评价：什么时候铁锁，什么时候戮力，都是要考虑的问题，用不好容易资敌，还容易烧到自己。",
	qunyou_sunxiu: "设计：？。<br>",
	qunyou_xiedaoyun: "设计：元徒。<br>评价：需要攒牌，否则就没牌印无懈和触发响应，但是在敌方连续使用锦囊时，一旦滚起来，就非常恐怖了，无懈需要的底牌越来越少，手上的牌越来越多，属于才女的应对自如十分有画面感。",
	qunyou_xiean: "设计：夏商周在。<br>陈郡谢氏中最强的，族谢安的公式打法就是，延后摸3牌，之后的摸牌都不延后->遇到弃牌就延后->用一张伤害牌，然后摸三弃三捡回这张伤害牌。",
	qunyou_xiexuan: "设计：拉普拉斯。<br>评价：有点弱了，印杀和桃的条件太苛刻，况且横置角色的条件也很难，如果把兵主不限次数，强度就正常了。",
	qunyou_zhaoyun: "设计：钟林。<br>评价：又有强度但也不至于太阴的设计。",
	qunyou_sunshao: "设计：叼五我爱你麻（B站）。<br>评价：实际上非常缺装备牌，导致二技能没牌可换，当然，过牌量不错。",
	qunyou_caocao: "设计：钟林。修改：欢愉与希望<br>加了个发动三次获得所有展示过的牌，解决了无结果问题",
    qunyou_xielingyun: "设计：混乱的啃<br>评价：额，你没那么多牌来调节全场，ai的不智能也导致这个武将的强度不好说",
	qunyou_xieshi: "设计：ff<br>评价：感觉有公式打法，注意不要资敌以及随机应变就行了",
	qunyou_spwenyang: "设计：昆世<br>评价：贴吧来的设计，如何让出牌带给你成就感？",
	qunyou_liukun: "欢愉与希望<br>“何意百炼刚，化为绕指柔。”",
	qunyou_sunjiao: "设计：杰劼夫长(贴吧）<br>评价：很好玩的发育将，前提是你要能发育起来",
	qunyou_luxun: "设计：BV1Rv7S65EAy<br>评价：永动而且阴",
	qunyou_caozhi: "设计：钟林<br>评价：阴",
	qunyou_simayi: "设计：迟眠饱（B站）<br>，来自BV1vk5G6AERQ。评价：挺看运气的，强度阳顶天",
	qunyou_haopu: "设计：yyuan<br>评价：很好的设计，但你必须要清楚什么时候拼输才行",
	qunyou_chenzhaoyun: "设计：0^0。<br>评价：挺好的设计，印牌很强",
	qunyou_wanglang: "设计：滑溜溜。<br>评价：阴完了，拿到A和K就能空城全场",
	qunyou_cbpzhaoyun: "设计：琉多斯&欢愉与希望。<br>评价：我也不知道我改的好不好",
	qunyou_jiangwei: "来源：BV1CDGv6uESF<br>吐槽：原版那描述都能自创好几个新概念了，还有，太弱了，共同拼点本来就不容易赢，自身顶多是小制衡，没有手牌还发动不了技能",
	qunyou_zhugeliang: "设计：寻辉逐烨<br>吐槽：太麻烦了，需要改进",
	qunyou_pengyue: "设计：鹭。<br>评价：实战似乎一般，心血来潮做的一个",
	qunyou_liumo: "设计：祂不想。<br>评价：十分好玩的设计，伪用一摸一，爽！",
	qunyou_mengliufeng: "设计：未知。<br>评价：拿一点体力上限换两张决斗。额，不好衡量，背景故事写的不错，但我没贴过来",
	qunyou_caoshuang: "设计：嘻˘꒳˘羲<br>评价：我也不知道有没有bug",
	qunyou_hanshiwuhu: "设计：佐世保之时雨。<br>评价：",
	qunyou_zhonghui: "设计：熏鱼不爱果子。修改：欢愉与希望<br>评价：我也不知道我改的好不好，总之比原版强了。",
	qunyou_yang_wang: "设计：西夏笠谷。<br>评价：有操作有强度",
	qunyou_xian_hua: "设计：西夏笠谷。<br>评价：有操作有强度",
	qunyou_sunce:"设计：西夏笠谷。<br>评价：",
	qunyou_lvlingqi:"设计：西夏笠谷。<br>评价：",
	qunyou_panjun:"设计：西夏笠谷。<br>评价：",
	qunyou_mojiangwei: "设计：墨客。<br>评价：对牌序要求也太高了，对运气要求也高",
	qunyou_guohuai: "设计：心乐之。<br>评价：沙摩柯和赵俨的私生子，其实强度不高，孩子们，我又卡基本牌了",
	qunyou_diaochan: "设计：来自大宝规则集中宗族技的例子<br>评价：自己有黑桃就先给自己用",
	qunyou_wuzhangfei: "设计：晴<br>评价：永动机，额，但是不知道怎么改",
	qunyou_weiguanyu: "设计：祭主<br>评价：很有新意，但是卡最大点了怎么办，也是一个待改进名单",
	qunyou_zhangyan: "设计：终汐舷<br>评价：阴，但是很爽",
	shanhe_zhangjiao: "设计：玖宴<br>评价：太好玩了，起义的强度是真高，另外ai比较笨，不会凑三类型，因此给多点人，可以很顺利获得起义",
	shanhe_luzhi: "设计：魁梧影<br>评价：需要控血线，封牌的确保证了强度，虽然是个摸牌白",
	shanhe_dongzhuo: "设计：玖宴<br>评价：一开始还以为只能配刘协，直到我发现扶主能重置，这下真成大汉忠良了",
	qunyou_lvyi: "设计：三天内炸白宫（B站）&& 欢愉与希望<br>说明：原技能来自BV1X5cozAEMH，说实话原技能有很多边界问题，装备牌怎么算？延时锦囊怎么算？闪和无懈怎么算？因此限定了牌的范围，非伤害牌要有角色目标，同时我还加了个技能补充强度",
	yachaiclan_cuiyan: "设计：崖柴xxxF（B站）",
	yachaiclan_wangxiang: "设计：崖柴xxxF（B站）",
	yachaiclan_diaochan: "设计：崖柴xxxF（B站）",
	yachaiclan_wuyi: "设计：崖柴xxxF（B站）",
	yachaiclan_xunyu: "设计：崖柴xxxF（B站）",
	yachaiclan_luxun: "设计：崖柴xxxF（B站）",
	yachaiclan_lukang: "设计：崖柴xxxF（B站）",
	yachaiclan_luji: "设计：崖柴xxxF（B站）",
	yachaiclan_luyun: "设计：崖柴xxxF（B站）",
	yachaiclan_luji2: "设计：崖柴xxxF（B站）<br>评价：该览的条件太苛刻了，同时收益也不高",
	yachaiclan_luyusheng: "设计：崖柴xxxF（B站）<br>",
	yachaiclan_lukai: "设计：崖柴xxxF（B站）<br>",
	yachaiclan_zhugeliang: "设计：崖柴xxxF（B站）<br>评价：原版强度并不高，将明亮出的牌并不一定总是能用，同时柱鼎又要求首次，你要用牌就得放弃柱鼎的补牌，只能说丞相就是鼎柱，宗族技只不过是人家没牌是补一下的工具罢了。<br>修改：加强将明，改成每回合限X次了，丞相理应如此",
	yachaiclan_zhugezhan: "设计：崖柴xxxF（B站）<br>评价：",
	qunyou_wangyun: "来源：BV12N9gBMEW2",
	qunyou_zhouyu: "设计：寻辉逐烨<br>评价：前两个出牌阶段开无中，能出杀就出，后两个出牌阶段就开始烧人了。还是有概率空城的，要注意玩法，小心卧龙诸葛和无懈",
};
