/** 武将称号 characterTitle */
export const characterTitle = {
	qunyou_wenyang: "独骑将军",
	qunyou_shibao: "乐陵郡公",
	qunyou_sunxiu: "紫气伤和",
	qunyou_xiedaoyun: "咏絮之才",
	qunyou_xiean: "雅志轩冕",
	qunyou_xiexuan: "芝兰玉树",
	qunyou_xielingyun: "不为之赋",
	qunyou_xieshi: "岁寒松柏",
	qunyou_zhaoyun: "炙龙烈胆",
	qunyou_sunshao: "创基扶政",
	qunyou_caocao: "山海归心",
	qunyou_spwenyang: "灭光破云",
	qunyou_liukun: "时穷节乃见",
	qunyou_simayi: "独水孤清",
	qunyou_sunjiao: "夏口门使",
	qunyou_luxun: "渊谋谦略",
	qunyou_caozhi: "酒虎诗龙",
	qunyou_haopu: "慰壑把晖",
	qunyou_chenzhaoyun: "坐收渔利",
	qunyou_wanglang: "渊薮临危",
	qunyou_cbpzhaoyun: "虎威将军",
	qunyou_jiangwei: "桀慢的麒麟",
	qunyou_zhugeliang: "武侯",
	qunyou_pengyue: "审时沉势",
	qunyou_liumo: "问琴雅然",
	qunyou_mengliufeng: "翔枝成凤",
	qunyou_caoshuang: "托孤傲臣",
	qunyou_hanshiwuhu: "屡败屡战",
	qunyou_zhonghui: "暂定",
	qunyou_yang_wang: "贤婉俭德",
	qunyou_xian_hua: "锦瑟良缘",
};
