/**
 * 武将译名、前缀键（与 lib.namePrefix 配合时可加 xxx_prefix）
 */
export const characterTranslate = {
	"群友设计": "群友设计",
	qunyou_wenyang: "文鸯",
	qunyou_shibao: "石苞",
	qunyou_sunxiu: "孙秀",
	qunyou_zhaoyun: "赵云",
	qunyou_sunshao: "孙绍",
	qunyou_caocao: "曹操",
	qunyou_spwenyang: "sp文鸯",
	qunyou_liukun: "刘琨",
	qunyou_simayi: "司马乂",
	qunyou_haopu: "郝普",
	qunyou_chenzhaoyun: "嗔赵云",
	qunyou_chenzhaoyun_prefix: "嗔",
	qunyou_xiedaoyun: "族谢道韫",
	qunyou_xiedaoyun_prefix: "族",
	qunyou_xiean: "族谢安",
	qunyou_xiean_prefix: "族",
	qunyou_xiexuan: "族谢玄",
	qunyou_xiexuan_prefix: "族",
	qunyou_xielingyun: "族谢灵运",
	qunyou_xielingyun_prefix: "族",
	qunyou_xieshi: "族谢石",
	qunyou_xieshi_prefix: "族",
	qunyou_sunjiao: "孙皎",
	qunyou_luxun: "陆逊",
	qunyou_caozhi: "曹植",
	qunyou_wanglang: "王朗",
	qunyou_cbpzhaoyun: "长坂坡赵云",
	qunyou_jiangwei: "姜维",
	qunyou_zhugeliang: "谋诸葛亮",
	qunyou_zhugeliang_prefix: "谋",
};
