/** 武将称号 characterTitle */
export const characterTitle = {
	qunyou_wenyang: "独骑将军",
	qunyou_shibao: "乐陵郡公",
	qunyou_sunxiu: "紫气伤和",
	qunyou_xiedaoyun: "咏絮之才",
	qunyou_xiean: "雅志轩冕",
	qunyou_xiexuan: "芝兰玉树",
	qunyou_xielingyun: "不为之赋",
	qunyou_xieshi: "岁寒松柏",
	qunyou_zhaoyun: "炙龙烈胆",
	qunyou_sunshao: "创基扶政",
	qunyou_caocao: "山海归心",
	qunyou_sp_wenyang: "灭光破云",
	qunyou_liukun: "时穷节乃见",
	qunyou_simayi: "独水孤清",
	qunyou_sunjiao: "夏口门使",
	qunyou_luxun: "渊谋谦略",
	qunyou_caozhi: "酒虎诗龙",
	qunyou_haopu: "慰壑把晖",
	qunyou_chen_zhaoyun: "坐收渔利",
	qunyou_wanglang: "渊薮临危",
	qunyou_cbp_zhaoyun: "虎威将军",
	qunyou_jiangwei: "桀慢的麒麟",
	qunyou_sb_zhugeliang: "炎汉挽歌",
	qunyou_pengyue: "审时沉势",
	qunyou_liumo: "问琴雅然",
	qunyou_meng_liufeng: "翔枝成凤",
	qunyou_caoshuang: "托孤傲臣",
	qunyou_hanshiwuhu: "屡败屡战",
	qunyou_zhonghui: "暂定",
	qunyou_yang_wang: "贤婉俭德",
	qunyou_caoxiancaohua: "锦瑟良缘",
	qunyou_mo_jiangwei: "赴焱窮奇",
	qunyou_sb_guohuai: "临危济难",
	qunyou_clan_diaochan: "诛魔成义",
	qunyou_wu_zhangfei: "烈武恒威",
	qunyou_v_guanyu: "美髯公",
	qunyou_xx_sunce: "平江东扫患寇",
	qunyou_lvlingqi: "红袖仗钺",
	qunyou_zhangyan: "轻勇骇势",
	shanhe_zhangjiao: "太平道人",
	shanhe_luzhi: "桢干质烈",
	shanhe_hanfu: "虎形羊质",
	shanhe_lusu: "文韬武略",
	shanhe_dongzhuo: "肃佞的辅相",
	qunyou_lvyi: "权伥",
	yachaiclan_cuiyan: "德音孔昭",
	yachaiclan_wangxiang: "伐冰之肇",
	yachaiclan_diaochan: "冲波逆折",
	yachaiclan_wuyi: "奉书献马",
	yachaiclan_xunyu: "芳兰生门",
	qunyou_zhouyu: "火计破曹",
	yachaiclan_luxun: "忠诚恳至",
	yachaiclan_lukang: "奕世载美",
	yachaiclan_luji2: "龙跃于江",
	yachaiclan_luyun: "荆衡杞梓",
	qunyou_panjun:"东吴之柱",
	yachaiclan_luji: "驽马逸足",
	yachaiclan_luyusheng: "邦士慕则",
	yachaiclan_lukai: "格业忠勤",
	yachaiclan_zhugeliang: "日月同悬",
	yachaiclan_zhugezhan: "掣近掎远",
	yachaiclan_zhugeshang: "跨父轶祖",
	yachaiclan_zhugejin: "才猷骏懋",
	yachaiclan_zhugeke: "枉恪罔逊",
	yachaiclan_zhugedan: "著勋齾铓",
	yachaiclan_zhugeliang2: "彪炳人寰",
	qunyou_wangyun: "今魂兴魄",
	zishu_liyan: "鄙情逐利",
	zishu_lvju: "克绍堂构",
	zishu_xunyu: "君去香留",
	zishu_sunhe: "阙储狩忌",
	zishu_zhangjinyun: "未落盛英",
	zhuoming_feili_gongsunyuan: "鸢飞戾灭",
	zhuoming_gongsunyuan: "狡投嗜欲",
	zhuoming_liuyan: "蟠虺望气",
	xiaobai_lizhaoyi: "兰女同烬",
	qunyou_clan_zhugejun: "三珠之隐根",
	qiufeng_zhangqiying: "三六大道",
	qiufeng_hushi: "杏惹妄疑",
	zishu_panshu: "瑶台遗韵",
	qunyou_taishici: "围阵奋戈",
	qunyou_sunce:"勇冠三江势",
	qunyou_guotu:"凶臣",
	qunyou_liuchen:"血溅轩辕",
	qunyou_masu:"兵法在胸",
	threed_dongbai:"渭浊阳关",
	threed_heji:"亭盖荧宫",
	shanhe_jiangwei:"宫锁透甲",
	shanhe_wangyi:"璟玉秋霜",
	xiaobai_lite:"六郡行王",
	xiaobai_suojing:"银钩铮骨",
	zishu_zangba:"泰山锁钥",
	zishu_duanjiong:"束马县锋",
	qunyou_guojia: "遗策定辽",
	zishu_shantao: "千仞振嵩",
	qunyou_zhaoshuang: "方圆演数",
	qiufeng_xiahouhui: "熠熠珠玉",
	qunyou_guanyu: "义武千秋",
	zishu_maohuanghou: "江心何怨",
	zishu_guli: "争舵快航",
	zhuoming_mateng: "驰陇横秋",
	zhuoming_fq_mateng: "边雁朔南",
	zhuoming_sc_mateng: "龙马腾云",
	xuandie_xunguan: "门蔻丰华",
	xuandie_lvzhi: "雌龙",
	xuandie_wenjun: "朱弦明镜",
	xuandie_zuti: "此非恶声",
	qunyou_zhongjin: "徒劳代逸",
	qunyou_feiyi: "止步无前",
	qunyou_clan_xunzhuan: "明允笃诚",
	qunyou_clan_wangrong: "璞隐九曲",
	qunyou_clan_yuantanshang: "常棣失华",
	zishu_yongkai: "腥麈啄碑",
	qunyou_yangqun: "力鸣截岳",
	qunyou_clan_yuanshao: "捷成族英",

	qunyou_clan_yuanshu: "鋩失权惘",
};
