import { get } from "noname";

// shanhe 前缀技能翻译（附属条目紧跟主条目）
export const shanheTranslate = {
	shanhe_chuandao: "传道",
	shanhe_chuandao_info: "出牌阶段，你可以将任意张手牌分配给其他角色并记录这些牌的花色。你以此法交出四种花色的牌后，若本回合你未因“传道”而摸过牌，你清除记录并摸X张牌（X为你本回合“传道”过的角色数且至多为3）。",
	shanhe_qiyi: "起义",
	shanhe_qiyi_info: "每回合各限一次，你于摸牌阶段外获得牌后，摸两张牌并分配给至多两名其他角色两张牌；你于弃牌阶段外失去牌后，对至多两名其他角色各造成1点雷电伤害。",
	shanhe_shifu: "施符",
	shanhe_shifu_info: "<b>锁定技</b>，其他角色于其回合外获得你的牌时，将牌置于其武将牌上称为“符”并令其回复1点体力；其回合开始时，交给你等量的牌（不足则全给），然后获得这些“符”并失去1点体力。",
	shanhe_muzhong: "募众",
	shanhe_muzhong_info: `<b>限定技</b>，出牌阶段，你可以令任意名对其发动过"传道"的角色依次展示并交给你一张牌，若你以此法获得的牌包含三种类型，你获得${get.poptip("shanhe_qiyi")}，否则你获得${get.poptip("shanhe_shifu")}。`,
	shanhe_zhenpan: "镇叛",
	shanhe_zhenpan_info: "准备阶段，你可以失去1点体力，然后你弃置X张牌并选择一名其他角色观看其手牌（X为你的体力值），该角色本回合不能使用或打出与你弃置花色相同的牌。",
	shanhe_zhenpan_ban: "镇叛·禁",
	shanhe_kangbian: "抗辩",
	shanhe_kangbian_info: "每回合限一次，你使用牌指定唯一目标或你成为【杀】的唯一目标时，你可与对方拼点，若你赢，你获得至多三名其他角色的各一张手牌，然后依次交给这些角色各一张牌；若你没赢，你失去1点体力。你可以使用本回合弃牌堆中的牌作为拼点牌。",
	shanhe_kangbian_pindian: "抗辩·拼点",
	shanhe_yinshan: "隐山",
	shanhe_yinshan_info: "结束阶段，你可以弃置所有手牌并摸已损失体力值数的牌。",
	shanhe_taoning: "讨佞",
	shanhe_taoning_info: "每回合限一次，你使用基本牌指定目标或成为无花色牌的目标时，你可以摸两张牌或对当前回合角色造成1点伤害。",
	shanhe_fuzhu: "扶主",
	shanhe_fuzhu_info: "每回合限一次，当你造成伤害后，你可以摸两张牌并交给\u201C拥立\u201D角色两张牌，然后令当前回合角色的一个描述含有出牌阶段限一次的技能视为未发动过。",
	shanhe_yunmo: "陨没",
	shanhe_yunmo_info: "锁定技，你受到锦囊牌造成的伤害加+1。",
	shanhe_yuanzhi: "渊峙",
	shanhe_yuanzhi_info: `锁定技，若场上武器牌多于防具牌，你视为拥有${get.poptip("xindangxian")}；若少于防具牌，你视为拥有${get.poptip("kunfen")}。`,
	shanhe_shutu: "殊途",
	shanhe_shutu_info: `锁定技，你的回合结束时，若本回合你体力值仅减少，你回复1点体力，然后视为使用一张【决斗】；若仅增加，你失去1点体力，然后视为使用一张【决斗】。`,
	shanhe_zijiu: "自鸠",
	shanhe_zijiu_info: `锁定技，若场上没有${get.poptip("shanhe_zijiu_jiu")}标记，你获得${get.poptip("shanhe_zijiu_jiu")}；当其他角色拥有${get.poptip("shanhe_zijiu_jiu")}时，其非锁定技失效。`,
	shanhe_zijiu_jiu: "鸠",
	shanhe_zijiu_jiu_info: `锁定技，你的黑色牌以正面朝上的形式离开你的手牌区时，你失去1点体力；当你体力流失时，弃置此标记。一名角色获得拥有"自鸠"技能的角色的黑色牌时，其获得此标记（场上至多存在3枚）。`,
	shanhe_huoyu: "惑語",
	shanhe_huoyu_info: `出牌阶段限X次，你可以与一名其他角色各摸一张牌，并视为对其使用一张【推心置腹】（X为你已损失的体力值）。`,
	shanhe_zhongzhe: "众谪",
	shanhe_zhongzhe_info: "锁定技，回合结束时，若你本回合使用过【五谷丰登】，你令所有未因此获得牌的角色议事。若结果为：黑色，意见为黑的角色各弃你一张手牌并各摸一张牌；红色，你交给意见为红的角色各一张牌并回复1点体力。",
	shanhe_jueliang: "脧粮",
	shanhe_jueliang_info: "出牌阶段限一次，你可以弃置任意张牌，视为使用一张额外亮出等量牌的【五谷丰登】。你使用的【五谷丰登】亮出时，你可以令此牌减少至多X个目标（X为你的当前体力值）。【五谷丰登】结算后，你可以获得置入弃牌堆的剩余牌。",
	shanhe_taolue: "韬略",
	shanhe_taolue_info: "锁定技，你使用单目标锦囊牌后，若目标角色与本回合上一次成为单目标锦囊牌的角色不同，你将手牌数较多一方的X张手牌交给另一方（X为双方手牌数差值一半，向上取整）。",
	shanhe_hezong: "合纵",
	shanhe_hezong_info: "转换技，出牌阶段，①你可以弃置一张牌并视为使用一张【声东击西】。②你可以弃置两张牌并令一名本回合未以此法使用过【树上开花】的角色视为使用一张【树上开花】。",
};
